env:
  node: true

plugins:
  - mocha
  - prettier

extends:
  - problems
  - prettier
  - plugin:mocha/recommended

parserOptions:
  sourceType: module
  ecmaVersion: 2020

rules:
  strict: 0
  prettier/prettier: error
  mocha/no-mocha-arrows: off
  mocha/no-skipped-tests: warn
  mocha/no-exclusive-tests: error
