name: Publish to NPM

on:
  push:
    branches: ["publish"]

env:
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  publish:
    if: ${{ github.ref == 'refs/heads/publish' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Create new release
        run: npm run release:create

      - name: Push release to GitHub
        run: git push --follow-tags origin master

      - name: Publish to npm
        run: npm run release:publish
