name: Run tests

on:
  - push
  - pull_request
  - workflow_dispatch
  - workflow_call

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: ["16.x", "17.x", "18.x", "lts/*"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install --package-lock false

      - name: Run tests
        run: npm test
